"""empty message

Revision ID: 38c070b15009
Revises: 6fe3f1a935ae
Create Date: 2018-06-27 09:55:14.867951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c070b15009'
down_revision = '6fe3f1a935ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_time', sa.Float(), nullable=True),
    sa.Column('main_team', sa.String(length=50), nullable=True),
    sa.Column('guest_team', sa.String(length=50), nullable=True),
    sa.Column('z_score', sa.Integer(), nullable=True),
    sa.Column('k_score', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('ball_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ball_id'], ['ball.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
