"""empty message

Revision ID: 398ff1939f7f
Revises: a451d5f9c479
Create Date: 2018-06-27 10:22:06.588385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398ff1939f7f'
down_revision = 'a451d5f9c479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_time', sa.Float(), nullable=True),
    sa.Column('main_team', sa.String(length=50), nullable=True),
    sa.Column('guest_team', sa.String(length=50), nullable=True),
    sa.Column('z_score', sa.Integer(), nullable=True),
    sa.Column('k_score', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
