"""empty message

Revision ID: 6fe3f1a935ae
Revises: 
Create Date: 2018-06-27 09:27:05.740137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe3f1a935ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ball',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('in_group', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_time', sa.Float(), nullable=True),
    sa.Column('main_team', sa.String(length=50), nullable=True),
    sa.Column('guest_team', sa.String(length=50), nullable=True),
    sa.Column('z_score', sa.Integer(), nullable=True),
    sa.Column('k_score', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ball_match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('ball_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ball_id'], ['ball.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'ball_id')
    )
    op.create_table('integral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrals', sa.String(length=50), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('lose', sa.String(length=50), nullable=True),
    sa.Column('clean', sa.String(length=50), nullable=True),
    sa.Column('ball_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ball_id'], ['ball.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integral')
    op.drop_table('ball_match')
    op.drop_table('match')
    op.drop_table('ball')
    # ### end Alembic commands ###
