"""empty message

Revision ID: a451d5f9c479
Revises: 38c070b15009
Create Date: 2018-06-27 10:14:08.921728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a451d5f9c479'
down_revision = '38c070b15009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_time', sa.Float(), nullable=True),
    sa.Column('main_team', sa.String(length=50), nullable=True),
    sa.Column('guest_team', sa.String(length=50), nullable=True),
    sa.Column('z_score', sa.Integer(), nullable=True),
    sa.Column('k_score', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ball_match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('ball_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ball_id'], ['ball.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'ball_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ball_match')
    op.drop_table('match')
    # ### end Alembic commands ###
